name: Your New Jekyll Site
markdown: kramdown
kramdown:
  parse_block_html: true
pygments: true
exclude: [README]
picture:
  source: assets/images/_fullsize
  output: assets/images/generated
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.5]
      attr:
        itemprop: "image"
        data-class: "image-responsive"
      source_default:
         width: "500"
         height: "500"
    img-featurette:
      ppi: [1, 1.5]
      attr:
        data-class: "featurette-image img-responsive"
      source_default:
        width: "500"
        height: "500" 
    img-circle:
      ppi: [1, 1.5]
      attr:
        data-class: "img-circle"
      source_default:
        width: "140"
        height: "140"
    img-carousel:
      ppi: [1, 1.5]
      source_default:
        width: "1920"
        height: "500"
    icon:
      ppi: [1, 1.5]
      attr:
        class: "icon"
        itemprop: "image"
      source_default:
        height: "35px"
